[project]
name = "pysmartdok"
version = "0.1.0"
description = "Smartdok client"
authors = [{ name = "David Skoland", email = "david.skoland@asterisk.digital" }]
requires-python = ">=3.11"

readme = "README.md"
license = { text = "MIT" }

dependencies = [
    "beautifulsoup4>=4.12.2",
    "requests>=2.32.5"
]

[build-system]
requires = ["setuptools>=75", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["pysmartdok*"]
