[tox]
envlist = py311

[testenv]
description = Run tests with pytest
package = editable
setenv = PYTHONPATH = {toxinidir}/src
allowlist_externals =
    uv
    pytest
commands_pre = uv sync
commands = pytest {posargs:tests}
