[tox]
envlist = py311
requires =
    tox>=4
    tox-uv>=1.25

[testenv]
description = Run tests with pytest
package = editable
setenv = PYTHONPATH = {toxinidir}/src
allowlist_externals = pytest
commands = pytest
